file_header_list = [
    "FileMetaInformationVersion",
    "MediaStorageSOPClassUID",
    "MediaStorageSOPInstanceUID",
    "TransferSyntaxUID",
    "ImplementationClassUID",
    "ImplementationVersionName",
    "SourceApplicationEntityTitle",
    "SendingApplicationEntityTitle",
    "ReceivingApplicationEntityTitle"
]


image_set_header_list = [
    "SOPClassUID",
    "SOPInstanceUID",
    "StudyDate",
    "SeriesDate",
    "AcquisitionDate",
    "ContentDate",
    "StudyTime",
    "SeriesTime",
    "AcquisitionTime",
    "ContentTime",
    "AccessionNumber",
    "Modality",
    "Manufacturer",
    "StationName",
    "StudyDescription",
    "SeriesDescription",
    "ManufacturerModelName",
    "Manufacturer",
    "IrradiationEventUID",
    "PatientName",
    "PatientID",
    "SoftwareVersions",
    "ImagerPixelSpacing",
    "TargetExposureIndex",
    "DeviationIndex",
    "PatientPosition",
    "ViewPosition",
    "Sensitivity",
    "StudyInstanceUID",
    "SeriesInstanceUID",
    "StudyID",
    "SeriesNumber",
    "AcquisitionNumber",
    "InstanceNumber",
    "PatientOrientation",
    "PhotometricInterpretation",
    "Rows",
    "Columns",
    "PixelSpacing",
    "PixelAspectRatio",
    "BitsAllocated",
    "BitsStored",
    "HighBit",
    "SmallestImagePixelValue",
    "LargestImagePixelValue",
    "WindowCenter",
    "WindowWidth",
    "RescaleIntercept",
    "RescaleSlope",
    "RescaleType",
    "LossyImageCompression"
]

OUTPUT_TEMPLATE = {
    "file_name": [],
    "basename": [],
    "file_size": [],
    "file_creation_date": [],
    "file_modification_date": [],
    "file_readable_status": [],
    "modality": [],
    "patient_name": [],
    "patient_id": [],
    "accession_number": [],
    "study_description": [],
    "series_description": [],
    "view_position": [],
    "patient_orientation": [],
    "patient_position": [],
    "study_date": [],
    "converted_date": [],
    "90_days_up": [],
    "90_days_down": [],
    "series_date": [],
    "content_date": [],
    "acquisition_date":[],
    "study_time": [],
    "series_time": [],
    "acquisition_time": [],
    "content_time": [],
    "station_name": [],
    "manufacturer_model_name": [],
    "manufacturer": [],
    "software_versions": [],
    "study_id": [],
    "study_instance_uid": [],
    "series_instance_uid": [],
    "acquisition_number": [],
    "series_number": [],
    "instance_number": [],
    "sop_class_uid": [],
    "sop_instance_uid": [],
    "irradiation_event_uid": [],
    "imager_pixel_spacing": [],
    "target_exposure_index": [],
    "deviation_index": [],
    "sensitivity": [],
    "photometric_interpretation": [],
    "rows": [],
    "columns": [],
    "pixel_spacing": [],
    "pixel_aspect_ratio": [],
    "bits_allocated": [],
    "bits_stored": [],
    "high_bit": [],
    "smallest_image_pixel_value": [],
    "largest_image_pixel_value": [],
    "window_center": [],
    "window_width": [],
    "rescale_intercept": [],
    "rescale_slope": [],
    "rescale_type": [],
    "lossy_image_compression": [],
    "file_meta_information_version": [],
    "media_storage_sop_class_uid": [],
    "media_storage_sop_instance_uid": [],
    "transfer_syntax_uid": [],
    "implementation_class_uid": [],
    "implementation_version_name": [],
    "source_application_entity_title": [],
    "sending_application_entity_title": [],
    "receiving_application_entity_title": [],
    "avg_color": [],
    "sd_color_per_row": [],
    "sd_color_per_col": [],
    "sd_color_of_rows": [],
    "sd_color_of_cols": [],
    "mean_of_sd_rows": [],
    "mean_of_sd_cols": [],
    "sd_color_overall": [],
    "min_color": [],
    "max_color": [],
    "color_delta": []

}
